stages:
  - deploy

pwd:
  stage: deploy
  script:
    - pwd
    - ls -al
    - git pull
    - docker compose down
    - ./init.sh

  rules:
    - if: '$CI_COMMIT_BRANCH == "anemometer.tyama.mydns.jp"'