services:
  nginx:
    image: nginx:1.13
    ports:
      - "${HTTP_PORT:-8000}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - django

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  django:
    build: ./django
    command: uwsgi --socket :8001 --module anemometer_server.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./anemometer_server:/code
      - ./static:/static
    expose:
      - "8001"
    env_file:
      - ./django/.env
    depends_on:
      - mysql

  grafana:
    image: grafana/grafana
    platform: linux/x86_64
    env_file:
      - ./grafana/.env
    ports:
    - '3000:3000'
