# Generated by Django 4.1 on 2023-11-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anemometor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.IntegerField(default=0)),
                ('Status', models.CharField(max_length=10)),
                ('LastUpdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Winddata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WindSpeed', models.FloatField()),
                ('Time', models.DateTimeField()),
                ('LHWD', models.BooleanField(default=True)),
                ('LD', models.BooleanField(default=True)),
                ('AID', models.IntegerField(default=0)),
            ],
        ),
    ]
